openapi: 3.0.1
info:
  title: open
  description: API Definition of open
  version: 1.0.0
servers:
- url: http://localhost:8290/open
paths:
  /:
    get:
      responses:
        default:
          description: Default response
