name: Build & Deploy to Minikube

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build Docker Image
      run: |
       docker build -t wso2mi-local:latest \
        --build-arg BASE_IMAGE=wso2/wso2mi:4.4.0 \
        -f deployment/docker/Dockerfile \
        deployment/docker/resources


    - name: Load Docker Image into Minikube
      if: runner.os == 'Linux'
      run: |
        minikube image load wso2mi-local:latest

    - name: Deploy to Minikube
      run: |
        kubectl apply -f k8s/deployment.yaml
