name: WSO2 MI CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: YourStrong!Passw0rd
        ports:
          - 1433:1433
        options: >-
          --health-cmd "echo > /dev/tcp/localhost/1433"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    steps:
    # 1. Checkout code
    - name: Checkout Repository
      uses: actions/checkout@v4

    # 2. Setup Java & Maven
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    # 3. Build CAR file
    - name: Build CAR
      run: mvn clean package

    # 4. Wait for MSSQL to be ready
    - name: Wait for MSSQL
      run: |
        echo "Waiting for MSSQL to be ready..."
        for i in {1..30}; do
          /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P YourStrong!Passw0rd -Q "SELECT 1" && break
          echo "Still waiting..."
          sleep 2
        done

    # 5. Run WSO2 MI in Docker (same network as services)
    - name: Run WSO2 MI
      run: |
        docker network connect $(docker network ls --filter name=github_network --format "{{.ID}}") $(docker ps -qf "ancestor=mcr.microsoft.com/mssql/server:2022-latest")
        docker run -d --name wso2mi \
          --network=$(docker network ls --filter name=github_network --format "{{.Name}}") \
          -p 8290:8290 -p 8253:8253 \
          -v ${{ github.workspace }}/target:/home/wso2carbon/wso2mi/repository/deployment/server/carbonapps \
          wso2/wso2mi:4.4.0

    # 6. Wait for MI to start
    - name: Wait for WSO2 MI
      run: sleep 30

    # 7. Test API endpoint
    - name: Test Data Service
      run: |
        RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8290/services/mssql/data)
        if [ "$RESPONSE" -ne 200 ]; then
          echo "❌ API test failed with HTTP code $RESPONSE"
          exit 1
        fi
        echo "✅ API test passed"

    # 8. Deploy to Production MI (only on main)
    - name: Deploy to Prod MI
      if: github.ref == 'refs/heads/main'
      run: |
        curl -u ${{ secrets.WSO2_USER }}:${{ secrets.WSO2_PASS }} \
          -T target/*.car \
          http://prod-mi.example.com:8290/carbonapps
